const FETCH_USERS = 'users/FETCH_USERS';
const FETCH_USERS_SUCCESS = 'users/FETCH_USERS_SUCCESS';
const FETCH_USERS_FAILED = 'users/FETCH_USERS_FAILED';


const FETCH_ONE = 'users/FETCH_ONE';
const FETCH_ONE_SUCCESS = 'users/FETCH_ONE_SUCCESS';
const FETCH_ONE_FAILED = 'users/FETCH_ONE_FAILED';


const EDIT_USERS = 'users/EDIT_USERS';
const EDIT_USERS_SUCCESS = 'users/EDIT_USERS_SUCCESS';
const EDIT_USERS_FAILED = 'users/EDIT_USERS_FAILED';



const DELETE_USERS = 'users/DELETE_USERS';
const DELETE_USERS_SUCCESS = 'users/DELETE_USERS_SUCCESS';
const DELETE_USERS_FAILED = 'users/DELETE_USERS_FAILED';


const CREATE_USERS = 'users/CREATE_USERS';
const CREATE_USERS_SUCCESS = 'users/CREATE_USERS_SUCCESS';
const CREATE_USERS_FAILED = 'users/CREATE_USERS_FAILED';


