const FETCH_TABLE = 'users/FETCH_TABLE';
const FETCH_TABLE_SUCCESS = 'users/FETCH_TABLE_SUCCESS';
const FETCH_TABLE_FAILED = 'users/FETCH_TABLE_FAILED';


const FETCH_ONE = 'users/FETCH_ONE';
const FETCH_ONE_SUCCESS = 'users/FETCH_ONE_SUCCESS';
const FETCH_ONE_FAILED = 'users/FETCH_ONE_FAILED';


const EDIT_TABLE = 'users/EDIT_TABLE';
const EDIT_TABLE_SUCCESS = 'users/EDIT_TABLE_SUCCESS';
const EDIT_TABLE_FAILED = 'users/EDIT_TABLE_FAILED';



const DELETE_TABLE = 'users/DELETE_TABLE';
const DELETE_TABLE_SUCCESS = 'users/DELETE_TABLE_SUCCESS';
const DELETE_TABLE_FAILED = 'users/DELETE_TABLE_FAILED';


const CREATE_TABLE = 'users/CREATE_TABLE';
const CREATE_TABLE_SUCCESS = 'users/CREATE_TABLE_SUCCESS';
const CREATE_TABLE_FAILED = 'users/CREATE_TABLE_FAILED';


